<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Carbon\Carbon;

class MasterBahanBakuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Data Bahan Baku (Total 272 item)
        $bahan_bakus = [
            ['kode_barang' => 'KH.01.001', 'nama_barang' => 'Beras putih (premium)', 'satuan' => 'KG', 'harga_beli_awal' => 16000, 'saldo_awal' => 50],
            ['kode_barang' => 'KH.01.002', 'nama_barang' => 'Beras putih (medium)', 'satuan' => 'KG', 'harga_beli_awal' => 18000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.003', 'nama_barang' => 'Beras merah', 'satuan' => 'KG', 'harga_beli_awal' => 35000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.004', 'nama_barang' => 'Beras hitam', 'satuan' => 'KG', 'harga_beli_awal' => 220000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.005', 'nama_barang' => 'Beras ketan putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.006', 'nama_barang' => 'Beras ketan hitam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.007', 'nama_barang' => 'Tepung beras', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.008', 'nama_barang' => 'Tepung ketan', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.009', 'nama_barang' => 'Mie beras', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.01.099', 'nama_barang' => 'Beras dan olahan padi-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.001', 'nama_barang' => 'Jagung pipil kering', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.002', 'nama_barang' => 'Jagung pipil segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.003', 'nama_barang' => 'Jagung manis segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.004', 'nama_barang' => 'Beras jagung', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.005', 'nama_barang' => 'Jagung giling', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.006', 'nama_barang' => 'Tepung jagung (maizena)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.007', 'nama_barang' => 'Tepung jagung lokal (cornmeal)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.02.099', 'nama_barang' => 'Jagung dan olahan-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.001', 'nama_barang' => 'Singkong segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.002', 'nama_barang' => 'Singkong kering/gaplek', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.003', 'nama_barang' => 'Tepung singkong (tapioka)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.004', 'nama_barang' => 'Mocaf', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.005', 'nama_barang' => 'Ubi jalar putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.006', 'nama_barang' => 'Ubi jalar kuning/oranye', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.007', 'nama_barang' => 'Ubi jalar ungu', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.008', 'nama_barang' => 'Kentang', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.009', 'nama_barang' => 'Talas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.010', 'nama_barang' => 'Ganyong', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.011', 'nama_barang' => 'Sagu basah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.012', 'nama_barang' => 'Tepung sagu', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.03.099', 'nama_barang' => 'Umbi umbian-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.001', 'nama_barang' => 'Tepung terigu protein rendah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.002', 'nama_barang' => 'Tepung terigu protein sedang', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.003', 'nama_barang' => 'Tepung terigu protein tinggi', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.004', 'nama_barang' => 'Tepung semolina', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.005', 'nama_barang' => 'Mie kering (non-instan)', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.006', 'nama_barang' => 'Spageti', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.007', 'nama_barang' => 'Makaroni', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.008', 'nama_barang' => 'Roti tawar', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.009', 'nama_barang' => 'Roti gandum', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.010', 'nama_barang' => 'Tepung panir', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.011', 'nama_barang' => 'Biskuit', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.012', 'nama_barang' => 'Bubur bayi', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.04.099', 'nama_barang' => 'Gandum dan olahan tepung-lainnya', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.001', 'nama_barang' => 'Oat (rolled oats)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.002', 'nama_barang' => 'Oat instan', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.003', 'nama_barang' => 'Sorgum biji', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.004', 'nama_barang' => 'Tepung sorgum', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.005', 'nama_barang' => 'Millet/jewawut biji', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.006', 'nama_barang' => 'Tepung millet', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'KH.05.099', 'nama_barang' => 'Sereal-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.001', 'nama_barang' => 'Ayam broiler utuh', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.002', 'nama_barang' => 'Fillet dada ayam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.003', 'nama_barang' => 'Paha ayam atas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.004', 'nama_barang' => 'Paha ayam bawah (drumstick)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.005', 'nama_barang' => 'Sayap ayam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.006', 'nama_barang' => 'Hati ayam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.007', 'nama_barang' => 'Ampela ayam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.008', 'nama_barang' => 'Telur ayam ras/negeri', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.009', 'nama_barang' => 'Telur ayam kampung', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.010', 'nama_barang' => 'Telur puyuh', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.011', 'nama_barang' => 'Sosis ayam', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.01.099', 'nama_barang' => 'Ayam dan olahannya-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.001', 'nama_barang' => 'Daging sapi segar (has luar/sirloin)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.002', 'nama_barang' => 'Daging sapi segar (has dalam/tenderloin)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.003', 'nama_barang' => 'Daging sapi segar (sandung lamur/brisket)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.004', 'nama_barang' => 'Daging sapi segar (paha)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.005', 'nama_barang' => 'Daging sapi giling', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.006', 'nama_barang' => 'Hati sapi', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.007', 'nama_barang' => 'Iga sapi', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.008', 'nama_barang' => 'Daging kerbau segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.009', 'nama_barang' => 'Daging kambing segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.010', 'nama_barang' => 'Daging domba segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.011', 'nama_barang' => 'Hati kambing', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.012', 'nama_barang' => 'Sosis sapi', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.02.099', 'nama_barang' => 'Daging sapi/kerbau/kambing-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.03.001', 'nama_barang' => 'Lele', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.03.002', 'nama_barang' => 'Nila', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 100],
            ['kode_barang' => 'PH.03.003', 'nama_barang' => 'Mujair', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.004', 'nama_barang' => 'Patin', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.005', 'nama_barang' => 'Gurame', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.006', 'nama_barang' => 'Mas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.007', 'nama_barang' => 'Gabus', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.008', 'nama_barang' => 'Fillet ikan tawar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.03.099', 'nama_barang' => 'Ikan air tawar-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.001', 'nama_barang' => 'Kembung', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.002', 'nama_barang' => 'Tongkol', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.003', 'nama_barang' => 'Cakalang', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.004', 'nama_barang' => 'Tuna', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.005', 'nama_barang' => 'Sarden/lemuru', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.006', 'nama_barang' => 'Bandeng', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.007', 'nama_barang' => 'Tenggiri', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.008', 'nama_barang' => 'Kakap', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.009', 'nama_barang' => 'Fillet ikan laut', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.04.010', 'nama_barang' => 'Ikan laut-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.001', 'nama_barang' => 'Udang segar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.002', 'nama_barang' => 'Udang beku', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.003', 'nama_barang' => 'Cumi-cumi', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.004', 'nama_barang' => 'Sotong', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.005', 'nama_barang' => 'Kepiting/rajungan', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.006', 'nama_barang' => 'Kerang hijau', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.007', 'nama_barang' => 'Kerang dara', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.05.099', 'nama_barang' => 'Produk perikanan lain-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.001', 'nama_barang' => 'Susu UHT full cream', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.002', 'nama_barang' => 'Susu UHT rendah lemak', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.003', 'nama_barang' => 'Susu pasteurisasi', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.004', 'nama_barang' => 'Susu bubuk', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.005', 'nama_barang' => 'Yogurt plain', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.006', 'nama_barang' => 'Keju cheddar', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.007', 'nama_barang' => 'Keju olahan (slice)', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PH.06.099', 'nama_barang' => 'Susu dan olahan-lainnya', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.001', 'nama_barang' => 'Kedelai biji kering', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.002', 'nama_barang' => 'Tempe', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.003', 'nama_barang' => 'Tahu putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.004', 'nama_barang' => 'Tahu kuning', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.005', 'nama_barang' => 'Tahu sutra', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.006', 'nama_barang' => 'Susu kedelai', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.007', 'nama_barang' => 'Tepung kedelai', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.01.099', 'nama_barang' => 'Kedelai dan olahannya-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.001', 'nama_barang' => 'Kacang tanah kupas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.002', 'nama_barang' => 'Kacang tanah dengan kulit', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.003', 'nama_barang' => 'Kacang hijau', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.004', 'nama_barang' => 'Kacang merah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.005', 'nama_barang' => 'Kacang tolo/tunggak', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.006', 'nama_barang' => 'Kacang hitam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.007', 'nama_barang' => 'Kacang arab/chickpea', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.008', 'nama_barang' => 'Kacang polong/pea', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.009', 'nama_barang' => 'Kacang mede', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.010', 'nama_barang' => 'Kacang almond', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.02.099', 'nama_barang' => 'Kacang kacangan-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.03.001', 'nama_barang' => 'Wijen', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.03.002', 'nama_barang' => 'Biji bunga matahari', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.03.003', 'nama_barang' => 'Chia seed', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.03.004', 'nama_barang' => 'Flaxseed', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'PN.03.099', 'nama_barang' => 'Biji-bijian dan produknya-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.001', 'nama_barang' => 'Bayam', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.002', 'nama_barang' => 'Kangkung', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.003', 'nama_barang' => 'Sawi hijau', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.004', 'nama_barang' => 'Sawi putih', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.005', 'nama_barang' => 'Pakcoy', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.006', 'nama_barang' => 'Selada', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.007', 'nama_barang' => 'Daun singkong', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.008', 'nama_barang' => 'Daun pepaya', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.009', 'nama_barang' => 'Kelor', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.010', 'nama_barang' => 'Katuk', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.011', 'nama_barang' => 'Seledri daun', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.012', 'nama_barang' => 'Brokoli', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.013', 'nama_barang' => 'Kembang kol', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.014', 'nama_barang' => 'Buncis', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.015', 'nama_barang' => 'Seledri batang', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.016', 'nama_barang' => 'Asparagus', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.01.099', 'nama_barang' => 'Sayuran daun/batang/bunga-lainnya', 'satuan' => 'IKAT', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.001', 'nama_barang' => 'Tomat', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.002', 'nama_barang' => 'Mentimun', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.003', 'nama_barang' => 'Terong ungu', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.004', 'nama_barang' => 'Terong hijau', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.005', 'nama_barang' => 'Cabai merah besar', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.006', 'nama_barang' => 'Cabai rawit', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.007', 'nama_barang' => 'Labu siam', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.008', 'nama_barang' => 'Pare', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.009', 'nama_barang' => 'Paprika', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.010', 'nama_barang' => 'Okra', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.011', 'nama_barang' => 'Wortel', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.012', 'nama_barang' => 'Lobak putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.013', 'nama_barang' => 'Bit', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.02.099', 'nama_barang' => 'Sayuran buah/umbi/akar-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.001', 'nama_barang' => 'Bawang merah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.002', 'nama_barang' => 'Bawang putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.003', 'nama_barang' => 'Bawang bombai', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.004', 'nama_barang' => 'Daun bawang', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.005', 'nama_barang' => 'Bawang prei', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.006', 'nama_barang' => 'Jahe', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.007', 'nama_barang' => 'Kunyit', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.008', 'nama_barang' => 'Lengkuas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.009', 'nama_barang' => 'Kencur', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.010', 'nama_barang' => 'Serai', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.011', 'nama_barang' => 'Temu kunci', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.012', 'nama_barang' => 'Kemiri', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.03.099', 'nama_barang' => 'Sayuran bawang dan aromatik lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.04.001', 'nama_barang' => 'Jamur tiram', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.04.002', 'nama_barang' => 'Jamur kancing', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.04.003', 'nama_barang' => 'Jamur kuping', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.04.004', 'nama_barang' => 'Jamur shiitake', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'SY.04.099', 'nama_barang' => 'Jamur-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.001', 'nama_barang' => 'Pisang ambon', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.002', 'nama_barang' => 'Pisang kepok', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.003', 'nama_barang' => 'Pisang raja', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.004', 'nama_barang' => 'Pepaya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.005', 'nama_barang' => 'Semangka', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.006', 'nama_barang' => 'Melon', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.007', 'nama_barang' => 'Mangga harum manis', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.008', 'nama_barang' => 'Mangga gedong', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.009', 'nama_barang' => 'Jeruk manis', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.010', 'nama_barang' => 'Jeruk keprok', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.011', 'nama_barang' => 'Jambu biji', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.012', 'nama_barang' => 'Jambu air', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.013', 'nama_barang' => 'Nanas', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.014', 'nama_barang' => 'Salak', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.015', 'nama_barang' => 'Rambutan', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.016', 'nama_barang' => 'Duku', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.017', 'nama_barang' => 'Sirsak', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.018', 'nama_barang' => 'Durian', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.019', 'nama_barang' => 'Manggis', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.020', 'nama_barang' => 'Alpukat', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.021', 'nama_barang' => 'Apel malang', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.022', 'nama_barang' => 'Buah naga merah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.023', 'nama_barang' => 'Buah naga putih', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.024', 'nama_barang' => 'Kedondong', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.025', 'nama_barang' => 'Markisa', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.026', 'nama_barang' => 'Belimbing', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.027', 'nama_barang' => 'Sawo', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.028', 'nama_barang' => 'Matoa', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.01.099', 'nama_barang' => 'Buah lokal-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.001', 'nama_barang' => 'Apel', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.002', 'nama_barang' => 'Pear', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.003', 'nama_barang' => 'Anggur merah', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.004', 'nama_barang' => 'Anggur hijau', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.005', 'nama_barang' => 'Kiwi', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BU.02.099', 'nama_barang' => 'Buah impor-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.001', 'nama_barang' => 'Minyak goreng sawit', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.002', 'nama_barang' => 'Minyak goreng campuran', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.003', 'nama_barang' => 'Minyak kelapa', 'satuan' => 'LITER', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.004', 'nama_barang' => 'Margarin', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.005', 'nama_barang' => 'Mentega (butter)', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.01.099', 'nama_barang' => 'Minyak dan lemak-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.02.001', 'nama_barang' => 'Garam beryodium', 'satuan' => 'PAK', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.02.002', 'nama_barang' => 'Gula pasir', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.02.003', 'nama_barang' => 'Gula merah/aren', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.02.004', 'nama_barang' => 'Madu', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.02.099', 'nama_barang' => 'Garam, gula, dan pemanis-lainnya', 'satuan' => 'KG', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.001', 'nama_barang' => 'Lada/merica bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.002', 'nama_barang' => 'Ketumbar bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.003', 'nama_barang' => 'Jinten bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.004', 'nama_barang' => 'Pala bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.005', 'nama_barang' => 'Kayu manis', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.006', 'nama_barang' => 'Cengkeh', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.007', 'nama_barang' => 'Kapulaga', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.008', 'nama_barang' => 'Daun salam kering', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.009', 'nama_barang' => 'Oregano', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.03.099', 'nama_barang' => 'Bumbu kering (rempah)-lainnya', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.001', 'nama_barang' => 'Kecap manis', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.002', 'nama_barang' => 'Kecap asin', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.003', 'nama_barang' => 'Saus sambal', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.004', 'nama_barang' => 'Saus tomat', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.005', 'nama_barang' => 'Saus tiram', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.006', 'nama_barang' => 'Cuka makan', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.007', 'nama_barang' => 'Mayones', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.04.099', 'nama_barang' => 'Bumbu cair, saus, dan kondimen-lainnya', 'satuan' => 'BOTOL', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.001', 'nama_barang' => 'Santan segar', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.002', 'nama_barang' => 'Santan instan cair', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.003', 'nama_barang' => 'Santan bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.004', 'nama_barang' => 'Kaldu bubuk ayam', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.005', 'nama_barang' => 'Kaldu bubuk sapi', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.006', 'nama_barang' => 'Kaldu jamur', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.007', 'nama_barang' => 'Agar-agar bubuk', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.008', 'nama_barang' => 'Gelatin', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.05.099', 'nama_barang' => 'Produk olahan dasar-lainnya', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.06.001', 'nama_barang' => 'Terasi', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.06.002', 'nama_barang' => 'Tauco', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.06.003', 'nama_barang' => 'Ragi roti', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.06.004', 'nama_barang' => 'Baking powder', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.06.099', 'nama_barang' => 'Bahan fermentasi/pelengkap-lainnya', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.001', 'nama_barang' => 'Air minum kemasan galon', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.002', 'nama_barang' => 'Air minum kemasan botol 2 liter', 'satuan' => 'DUS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.003', 'nama_barang' => 'Air minum kemasan botol 1,5 liter', 'satuan' => 'DUS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.004', 'nama_barang' => 'Air minum kemasan botol 600 ml', 'satuan' => 'DUS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.005', 'nama_barang' => 'Air minum kemasan botol 330 ml', 'satuan' => 'DUS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.006', 'nama_barang' => 'Air minum kemasan cup', 'satuan' => 'DUS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.007', 'nama_barang' => 'Minuman kemasan botol/kaleng', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.008', 'nama_barang' => 'Susu kental manis', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.099', 'nama_barang' => 'Bahan minuman pendamping-lainnya', 'satuan' => 'PCS', 'harga_beli_awal' => 15000, 'saldo_awal' => 0],
            ['kode_barang' => 'BB.07.100', 'nama_barang' => 'Ayam giling', 'satuan' => 'KG', 'harga_beli_awal' => 13000, 'saldo_awal' => 0],
        ];

        $dataToInsert = array_map(function ($item) use ($now) {
            return array_merge($item, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $bahan_bakus);

        // --- Eksekusi ---
        Schema::disableForeignKeyConstraints(); 
        DB::table('master_bahan_bakus')->truncate(); 
        Schema::enableForeignKeyConstraints(); 

        foreach (array_chunk($dataToInsert, 100) as $chunk) {
            DB::table('master_bahan_bakus')->insert($chunk); 
        }

        $this->command->info('Berhasil menyisipkan ' . count($bahan_bakus) . ' data ke tabel master_bahan_bakus!');
    }
}